### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by PIXPOINT** [rdlabo-team/capacitor-screenshot-event#1]
Hi, any tips how to use this plugin or to use it?

**Comment by blinkdagger182** [comment]
Anyone able to get this running? function is not triggering

**Comment by technophilix** [comment]
> Anyone able to get this running? function is not triggering

Please use original one 'cordova-plugin-ios-detect-screenshot'
 first install it through `npm install cordova-plugin-ios-detect-screenshot` then use
 
```
 window.addEventListener('screenshotDidTake', () =>{
// your code to do
}, false)
```
in React or 
```
document.addEventListener('screenshotDidTake', () =>{
// your code to do
}, false)
``` 
in html cordova

**Comment by josephvoxone** [comment]
@technophilix any ideas for android?

**Comment by adamk22** [comment]
The documentation is kind of lacking for this specifically, but I ended up getting it to work with the latest version (`3.0.0`). For those that are wondering: 

I created a service for this specifically:

```
@Injectable()
export class ScreenshotService {
  private protecting = false;
  private questionId: string | undefined;

  constructor() {}

  async protect(enable: boolean) {
    if (!this.protecting && enable) {
      await ScreenshotEvent.startWatchEvent();
      ScreenshotEvent.addListener('userDidTakeScreenshot', this.handler);
      this.protecting = true;
    } else if (this.protecting && !enable) {
      await ScreenshotEvent.removeWatchEvent();
      this.protecting = false;
    }
  }

  private handler = () =>
    handler();
}

async function handler() {
 // TODO: This handler will be called when a screenshot has been made
}
```

I havent tested this for android, but I've resorted on using `@capacitor-community/privacy-screen` for android to disable screenshots completely.

**Comment by rdlabo** [comment]
I updated the README and made a demo app again. Please take advantage of it.

**Comment by rdlabo** [comment]
https://github.com/rdlabo-team/capacitor-screenshot-event
